#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "Build / Python-only (master, PyPy 3.8/Python 3.10/Python 3.11/Python 3.12)"

on:
  workflow_call:
    inputs:
      java:
        required: false
        type: string
        default: 17
      branch:
        description: Branch to run the build against
        required: false
        type: string
        # Change 'master' to 'branch-4.0' in branch-4.0 branch after cutting it.
        default: master
      hadoop:
        description: Hadoop version to run with. HADOOP_PROFILE environment variable should accept it.
        required: false
        type: string
        default: hadoop3
      envs:
        description: Additional environment variables to set when running the tests. Should be in JSON format.
        required: false
        type: string
        default: '{}'
      jobs:
        description: >-
          Jobs to run, and should be in JSON format. The values should be matched with the job's key defined
          in this file, e.g., build. See precondition job below.
        required: false
        type: string
        default: ''

jobs:
  run-build:
    strategy:
      matrix:
        pyversion: ["pypy3,python3.10", "python3.11", "python3.12"]
    permissions:
      packages: write
    name: Run
    uses: ./.github/workflows/build_and_test_ref.yml
    if: github.repository == 'apache/spark'
    with:
      java: 17
      branch: master
      hadoop: hadoop3
      envs: >-
        {
          "PYTHON_TO_TEST": "${{ matrix.pyversion }}"
        }
      jobs: >-
        {
          "pyspark": "true"
        }
