name: Notify test workflow
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    name: Notify test workflow
    runs-on: ubuntu-20.04
    steps:
      - name: "Notify test workflow"
        uses: actions/github-script@v3
        if: ${{ github.base_ref == 'master' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const endpoint = "GET /repos/:owner/:repo/actions/workflows/:id/runs?&branch=:branch"

            // TODO: Should use pull_request.user and pull_request.user.repos_url?
            // If a different person creates a commit to another forked repo,
            // it would be able to detect.
            const params = {
              owner: context.payload.pull_request.head.repo.owner.login,
              repo: context.payload.pull_request.head.repo.name,
              id: "build_and_test.yml",
              branch: context.payload.pull_request.head.ref,
            }

            const runs = await github.request(endpoint, params)
            const runID = runs.data.workflow_runs[0].id
            const runUrl = "https://github.com/"
              + context.payload.pull_request.head.repo.full_name
              + "/actions/runs/"
              + runID

            const name = 'Build and test'
            const head_sha = context.payload.pull_request.head.sha
            const status = 'in_progress'

            github.checks.create({
              ...context.repo,
              name,
              head_sha,
              status,
              output: {
                title: 'Test results',
                summary: runUrl,
                text: JSON.stringify({
                  owner: context.payload.pull_request.head.repo.owner.login,
                  repo: context.payload.pull_request.head.repo.name,
                  run_id: runID
                })
              }
            })
