name: Close stale PRs

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: |
          We're closing this PR because it hasn't been updated in a while.
          This isn't a judgement on the merit of the PR in any way. It's just
          a way of keeping the PR queue manageable.

          If you'd like to revive this PR, please reopen it!
        days-before-stale: 3650
        days-before-close: 3
